version: '3.1'
services:
  postgres:
    container_name: plpython3
    build:
      context: .
      dockerfile: plpython3.dockerfile
    restart: always
    volumes:
      - ./src:/src
      - ./benchmark:/benchmark
      - ./data:/data
    ports:
      - 5432:5432
